### ISSUE TITLE
Go pkgsite doesn't pickup documentation

### ISSUE THREAD

**Issue by jsimnz** [go-bond/bond#105]
[pkg.go.dev](https://pkg.go.dev/github.com/go-bond/bond) for bond doesn't render the documentation due to "License restrictions". If it can't find a license, it doesn't assume, and just throws this generic error.

Caused by the latest tag `0.1.42` being released before the `LICENSE` was added. Simply releasing a new tag should fix it 👍

**Comment by pkieltyka** [comment]
tagged v0.1.43
