### ISSUE TITLE
Prevent unintended pebble format updates

### ISSUE THREAD

**Issue by marino39** [go-bond/bond#124]
It may happen that ``pebble.Options{}.FormatMajorVersion`` changes and triggers an unintended update.

To prevent that we could store the pebble format version in a file ``data/bond/pebble_format_version``. If the file does not exist it would put the current format version number in. In the opposite situation, it would prevent bond from opening the pebble database.

I believe the best place to do this is in ``bond.Open`` after getting merged ``pebble.Options`` and just before opening pebble database. If version are different it should error out with a message ``pebble format version does not match: a != b``

In addition to that we should provide a way to update pebble format version in a controlled way. Temporarily it can be ``bond.MigratePebbleFormatVersion(opt bond.Options) error``. However, in the future should be done based on Migrations mechanism that we currently do not have.

**Comment by pkieltyka** [comment]
should we also have in bond.Open() perhaps a maxTargetPebbleMajorVersion or something..? so like, if someone passed a config, and they knew the max version was compatible, then on bond.Open() .. it would migrate + print a log, otherwise it would error the version doesn't match..? this might be the easiest way to handle migrations..

**Comment by marino39** [comment]
I would rather allow to read pebble format version from bond dir and allow to do migration. I do not want to create overrides. It should be plain and simple e.g.

```golang
var bondDirectory := "./bond"

if bond.PebbleFormatVersion(bondDirectory) < 14 {
   bond.MigratePebbleFormatVersion(pebbleOptionsV14)
}

db, err := bond.Open(bondDirectory, pebbleOptionsV14)
```

WDYT?

**Comment by pkieltyka** [comment]
nice. i like this. very good.
